import { describe, expect, it } from "bun:test"

describe("Tauri bridge contract", () => {
  it("exposes Cloudflare Tunnel capability and invoke commands", async () => {
    const source = await Bun.file("src-tauri/src/lib.rs").text()

    expect(source).toContain('"canManageCloudflareTunnel": true')
    expect(source).toContain("fn get_cloudflare_tunnel_status")
    expect(source).toContain("fn save_cloudflare_tunnel_config")
    expect(source).toContain("fn create_cloudflare_tunnel_plan")
    expect(source).toContain("fn start_cloudflare_tunnel")
    expect(source).toContain("fn stop_cloudflare_tunnel")
    expect(source).toContain("fn retry_cloudflare_tunnel_step")
    expect(source).toContain("fn list_desktop_tunnel_devices")
    expect(source).toContain("fn provision_desktop_tunnel")
    expect(source).toContain("fn send_desktop_tunnel_heartbeat")
    expect(source).toContain("fn delete_desktop_tunnel_device")
    expect(source).toContain("fn start_desktop_auto_tunnel")
    expect(source).toContain("DESKTOP_TUNNEL_SERVER_URL")
    expect(source).toContain("DESKTOP_TUNNEL_DEVICE_TOKEN")
    expect(source).toContain("ureq::post")
    expect(source).toContain("Command::new")
    expect(source).toContain("TcpStream::connect")
    expect(source).toContain("fn can_reuse_opencode_port(port: u16) -> bool")
    expect(source).toContain("fn is_password_protected_opencode_response(response: &str) -> bool")
    expect(source).toContain("GET / HTTP/1.1")
    expect(source).toContain("contains(\"opencode\")")
    expect(source).toContain("contains(\"401\")")
    expect(source).toContain("contains(\"login\")")
    expect(source).toContain("OpenCode reused")
    expect(source).toContain("OPENCODE_SERVER_PASSWORD")
    expect(source).toContain("OpenCode password is required before starting frpc")
    expect(source).toContain("fn save_frp_config(config: serde_json::Value, raw_config: Option<String>)")
    expect(source).toContain("createDesktopAutoTunnelOrchestrator")
    expect(source).toContain('"tunnelStatus": "error"')
    expect(source).toContain("Desktop auto tunnel requires the TypeScript desktop runtime bridge")
    expect(source).not.toContain('format!("https://{}.frp.local"')
    expect(source).not.toContain('"tunnelStatus": "connected"')
    expect(source).not.toContain('"publicUrl": "https://desktop-local.frp.local"')
    expect(source).not.toContain('"lastHeartbeatAt": "2026-05-25T00:00:00.000Z"')
    expect(source).not.toContain("Desktop tunnel provisioning requires the TypeScript desktop runtime bridge")
    expect(source).toContain("fn get_security_checks")
    expect(source).toContain("fn get_backup_summary")
    expect(source).toContain("fn run_manual_backup")
    expect(source).toContain("fn cleanup_old_backups")
    expect(source).toContain("fn get_diagnostics")
    expect(source).toContain("get_cloudflare_tunnel_status,")
    expect(source).toContain("save_cloudflare_tunnel_config,")
    expect(source).toContain("create_cloudflare_tunnel_plan,")
    expect(source).toContain("start_cloudflare_tunnel,")
    expect(source).toContain("stop_cloudflare_tunnel,")
    expect(source).toContain("retry_cloudflare_tunnel_step,")
    expect(source).toContain("list_desktop_tunnel_devices,")
    expect(source).toContain("provision_desktop_tunnel,")
    expect(source).toContain("send_desktop_tunnel_heartbeat,")
    expect(source).toContain("delete_desktop_tunnel_device,")
    expect(source).toContain("start_desktop_auto_tunnel,")
    expect(source).toContain("get_security_checks,")
    expect(source).toContain("get_backup_summary,")
    expect(source).toContain("run_manual_backup,")
    expect(source).toContain("cleanup_old_backups,")
    expect(source).toContain("get_diagnostics,")
    expect(source).not.toContain("tauri_plugin_shell")
    expect(await Bun.file("src-tauri/Cargo.toml").text()).not.toContain("tauri-plugin-shell")
    expect(await Bun.file("src-tauri/Cargo.toml").text()).toContain("ureq")
    expect(await Bun.file("src-tauri/capabilities/default.json").text()).not.toContain("shell:default")
  })
})
