import { describe, expect, it } from "bun:test"

describe("Tauri bridge contract", () => {
  it("exposes Cloudflare Tunnel capability and invoke commands", async () => {
    const source = await Bun.file("src-tauri/src/lib.rs").text()

    expect(source).toContain('"canManageCloudflareTunnel": true')
    expect(source).toContain("fn get_cloudflare_tunnel_status")
    expect(source).toContain("fn save_cloudflare_tunnel_config")
    expect(source).toContain("fn create_cloudflare_tunnel_plan")
    expect(source).toContain("fn start_cloudflare_tunnel")
    expect(source).toContain("fn stop_cloudflare_tunnel")
    expect(source).toContain("fn retry_cloudflare_tunnel_step")
    expect(source).toContain("fn get_security_checks")
    expect(source).toContain("fn get_backup_summary")
    expect(source).toContain("fn run_manual_backup")
    expect(source).toContain("fn cleanup_old_backups")
    expect(source).toContain("fn get_diagnostics")
    expect(source).toContain("get_cloudflare_tunnel_status,")
    expect(source).toContain("save_cloudflare_tunnel_config,")
    expect(source).toContain("create_cloudflare_tunnel_plan,")
    expect(source).toContain("start_cloudflare_tunnel,")
    expect(source).toContain("stop_cloudflare_tunnel,")
    expect(source).toContain("retry_cloudflare_tunnel_step,")
    expect(source).toContain("get_security_checks,")
    expect(source).toContain("get_backup_summary,")
    expect(source).toContain("run_manual_backup,")
    expect(source).toContain("cleanup_old_backups,")
    expect(source).toContain("get_diagnostics,")
    expect(source).not.toContain("tauri_plugin_shell")
    expect(await Bun.file("src-tauri/Cargo.toml").text()).not.toContain("tauri-plugin-shell")
    expect(await Bun.file("src-tauri/capabilities/default.json").text()).not.toContain("shell:default")
  })
})
